blank_issues_enabled: false
contact_links:
  - name: Big Video on Discord
    url: https://discord.com/channels/732586315836817469/846814633105031180
    about: Please ask and answer questions on the CAVA360VR Discord channel
