theme: jekyll-theme-modernist
title: CAVA360VR2.0 help guide
description: Help pages for CAVA2.0
URL: "https://bigsoftvideo.github.io/CAVA360VR2.0"
image: "media/logo.png"
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - contributing.md
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
